tasks:
- init: virtualenv -p python3 my-venv; export PIP_USER=no; source my-venv/bin/activate; pip install -r requirements.txt
  command: export PIP_USER=no; source my-venv/bin/activate
vscode:
  extensions:
    - ms-pyright.pyright@1.1.7:aew2YmhA2nD54Oyukn7OAg==